Disposeが1回だけしかよばれないBaseクラスを追加してFrameworkに適用する
extreal-dev/Extreal.Core.Common pull request #1
Opened 2023-01-18 02:21 UTC by sus-taguchi-t

# 何の変更を加えましたか？

- フォーマッタを導入しました
- 静的解析を導入しました
- アセンブリ定義の自動チェックを導入しました
- `DisposableBase` を実装しました
- 自動テストを実装しました

# 何を確認しましたか?

## 実装
- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
## テスト
- [x] 全ての自動テストが成功することを確認しました
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました
## 変更影響
- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

- [ ] 仕様はこれで大丈夫でしょうか？
- [ ] 何か気になる点はありますか？

2023-01-18 06:08 UTC, kiyohome requested changes

2023-01-18 06:08 UTC, kiyohome commented on package.json
> +  "version": "1.0.0",
0.1.0から始めた方がいいと思いました。

2023-01-18 06:08 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +
ファイナライザーが必要な場合の話しなんですが、ファイナライザーをBaseクラスに定義しても大丈夫そうですが、ダメでしょうか？
https://qiita.com/hkuno/items/e35c7e306e852ced375d

2023-01-18 06:08 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +            if (disposing)
disposingが必要な理由（FreeManagedResourcesが必要な理由）が理解できてないです。

[アンマネージドリソースを持つ場合の実装](https://qiita.com/hkuno/items/e35c7e306e852ced375d#%E3%82%A2%E3%83%B3%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%89%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%92%E6%8C%81%E3%81%A4%E5%A0%B4%E5%90%88%E3%81%AE%E5%AE%9F%E8%A3%85)
```
それは、プログラムがDispose()を呼ぶ前にGCがインスタンスを廃棄すると、インスタンスが持っているアンマネージドリソースが永遠に解放されない（リソースリーク）問題を避けるためです。
Dispose() と ファイナライザ(デストラクタ) の二か所でアンマネージドリソースの解放処理を行うことでも回避できますが、二か所に同じ処理を書くのは保守性が悪いので、一か所でまとめて処理するための仕組みなのです。
```

`Dispose() と ファイナライザ(デストラクタ) の二か所でアンマネージドリソースの解放処理を行うことでも回避できますが`でいいと思うのですが、何か問題があるんですかね。

2023-01-18 07:46 UTC, sus-taguchi-t commented on package.json
> +  "version": "1.0.0",
分かりました。修正します。

2023-01-18 07:48 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +
確かにファイナライザは継承を辿って順に親のファイナライザを呼び出すようですね。
Base クラスで定義しましょう。
https://learn.microsoft.com/ja-jp/dotnet/csharp/programming-guide/classes-and-structs/finalizers

2023-01-18 07:49 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +            if (disposing)
アンマネージドとマネージドを区別する必要性が私もよく分からないので、統一しましょう。
`disposing` はなくします。

2023-01-18 07:54 UTC, sus-taguchi-t commented on package.json
> +  "version": "1.0.0",
修正しました！
https://github.com/extreal-dev/Extreal.Core.System/pull/1/commits/9c5c6fdfa17cf8077825e1625c918beb0e5273f1

2023-01-18 07:54 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +
修正しました！
https://github.com/extreal-dev/Extreal.Core.System/pull/1/commits/fd6346d91d73c0d63ce50b46c1460b6772b8b1ae

2023-01-18 07:54 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +            if (disposing)
修正しました！
https://github.com/extreal-dev/Extreal.Core.System/pull/1/commits/fd6346d91d73c0d63ce50b46c1460b6772b8b1ae

2023-01-23 02:59 UTC, kiyohome requested changes

2023-01-23 02:59 UTC, kiyohome commented on Tests/Runtime/DisposableBaseTest.cs
> +    public class DisposableBaseTest
usingステートでもFreeResourcesが呼ばれることを確認するテストケースがあった方がいいと思います。
https://qiita.com/Nossa/items/947f8985e4d5f13d9bc2

2023-01-23 06:27 UTC, sus-taguchi-t commented on Tests/Runtime/DisposableBaseTest.cs
> +    public class DisposableBaseTest
そうですね。
追加します。

2023-01-23 06:29 UTC, sus-taguchi-t commented on Tests/Runtime/DisposableBaseTest.cs
> +    public class DisposableBaseTest
修正しました。
https://github.com/extreal-dev/Extreal.Core.System/pull/1/commits/80582d9736decc3ccf0b59937bc3111e242586b2

2023-01-23 06:56 UTC, kiyohome requested changes

2023-01-23 06:56 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +    /// </summary>
このクラスの処理内容とメッセージをクラスコメントで伝えた方がいいと思いました。こんなイメージです。
```
Disposeを安全に行うためにベースクラスで次の処理を提供します。
- Disposeが複数回呼ばれても1度しか実行しない
- ファイナライザーでDisposeを呼び出す
- このクラスのファイナライズを抑制する
このBaseクラスを継承しFreeResourcesメソッドにリソース解放処理を実装してください。FreeResourcesメソッドでは例外を発生しないようにして、全てのリソースが解放されるように実装してください。
```

2023-01-23 08:30 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +    /// </summary>
`FreeResources` メソッドにも「例外を出させない」という旨を記述する。

2023-01-23 08:33 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +    /// </summary>
修正しました！
https://github.com/extreal-dev/Extreal.Core/pull/1/commits/629caedccb155af2018ba09264e62d3f7660bf34

2023-01-24 00:37 UTC, kiyohome requested changes

2023-01-24 00:37 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +            DisposeInternal();
このあたりのやりとりを見ると、アンマネージドなリソースの解放にはDisposeパターンが必要、マネージドなリソースだけならDisposeパターンは不要みたいですね。
https://atmarkit.itmedia.co.jp/bbs/phpBB/viewtopic.php?topic=45412&forum=7
アンマネージドなリソースの解放→ファイナライザorDisposeメソッド
マネージドなリソースの解放→Disposeメソッドのみ（ファイナライザでやったらダメ）

マネージドなリソースはIDisposableを実装しているクラスのようです。

現状のExtrealでアンマネージドなリソースを直接扱うケースがなければこの対応自体不要と思いますがいかがでしょうか？

2023-01-24 00:57 UTC, sus-taguchi-t commented on Runtime/DisposableBase.cs
> +            DisposeInternal();
> マネージドなリソースはIDisposableを実装しているクラスのようです。

これを定義とすると全体的にしっくりくる気がします。

>現状のExtrealでアンマネージドなリソースを直接扱うケースがなければこの対応自体不要と思いますがいかがでしょうか？

確かにアンマネージドリソース（主に `IntPtr`）を扱う場面はあまり想像できないので、あまり `DisposableBase` の恩恵はなさそうですね。
「複数回 `Dispose` メソッドが呼ばれても最初の呼び出し以外は無効」であることと「`Dispose` メソッドの中では例外を投げさせない」ことを徹底できれば問題ないと思います。

2023-01-24 02:41 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +            DisposeInternal();
話し合って下記の対応としました。
- 複数回Dispose呼び出しとかDisposeパターンのルールを徹底したいのでDisposeパターンの対応を入れる
- Disposeのために継承が使えなくなるのはあまりよろしくないので横出しして移譲するかたちにする
- Holidayで実践してみてライブラリへの取り込みを検討する

2023-01-25 07:53 UTC, kiyohome commented on Runtime/DisposableBase.cs
> +            DisposeInternal();
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/2
確認が取れたのでクローズします。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:9ea0cf1287a9c944c989c3cff60f15f3"
`Use GUIDs` のチェックが外れていません。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Runtime/System/DisposableBase.cs
> +        protected DisposableBase()
Create -> Create***s***

私は他のライブラリでは "(This method) creates a new DisposableBase." という意図を込めて "Create***s***" としており、"Create" だとどちらかというと「（私が）します」「（あなたが）してください」といったニュアンスになると思っています。

他のメソッドのドキュメントも同様です。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Runtime/System/SafeDisposer.cs
> +        /// <param name="releaseUnmanagedResources">Process to release unmanaged resources.</param>
Process -> Processing

メソッドを指す「処理」としては "Process" （過程・工程の方が意味が近い）よりも "Processing" の方が良いと思います。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:b8d918b3ff5e05e4ba23a5c2512f52fe",
`Extreal.Core.Logging` に依存するということは `Extreal.Core.Logging` でこの `Common` を使用できないことを指しますが、問題ないでしょうか？
つまり FW の 1 番ベースとなるライブラリは `Common` でなく `Logging` にとなるということです。

これを回避するためにはこの `Extreal.Core.Logging` への参照を外して `Common` にログ出力をおこなわせることを断念するか、`Extreal.Core.Logging` を `Extreal.Core.Common` に合併するかの 2 択があります。
後者を選ぶと早速後方互換が崩れますが、個人的にはこちらの方が設計はきれいだと感じています。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Tests/Runtime/Extreal.Core.Common.Test.asmdef
> +    ],
テストコードは静的解析を見なくて良いのでしょうか？

2023-01-26 03:34 UTC, sus-taguchi-t commented on Tests/Runtime/System/ClassWithUnmanaged.cs
> +        protected override void ReleaseUnmanagedResources() => ++UnmanagedTimes;
他のクラスではインクリメント演算子を後置していましたが、ここで前置している意図は何かありますでしょうか？

2023-01-26 03:34 UTC, sus-taguchi-t commented on Tests/Runtime/System/DisposableBaseTest.cs
> +            }
`GC.WaitForPendingFinalizers` メソッドを使用する場合は `yield return null` で遅延させなくても正しく挙動たので、ここにある `yield return null` はすべて不要です。
`yield return null` をすべて削除する場合このメソッドの返値の型は `void`、属性は `[Test]` にする必要があります。

他のメソッドでも同様です。

2023-01-26 03:34 UTC, sus-taguchi-t commented on Tests/Runtime/System/DisposableBaseTest.cs
> +        }
>// Managedが呼ばれないことをテストしたいため、
// 確実ではありませんが待つためにUnmanagedを使用

この説得力を増させるためには `sut2` の `Dispose` メソッドは呼ばずに、`GC.WaitForPendingFinalizers` メソッド呼び出しの前後で `ClassWithUnmanaged.UnmanagedTimes` が増加することをアサートした方が良いと思いました。

2023-01-26 03:45 UTC, kiyohome commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:9ea0cf1287a9c944c989c3cff60f15f3"
すみません、修正しました。
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/6a7c7a527da086f20d57676d6236dd59a6d1a459

2023-01-26 03:50 UTC, kiyohome commented on Runtime/System/DisposableBase.cs
> +        protected DisposableBase()
修正しました！
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/d7e19839f80f37a3fc4a3937bd4c1b45af533cf0

2023-01-26 03:53 UTC, kiyohome commented on Runtime/System/SafeDisposer.cs
> +        /// <param name="releaseUnmanagedResources">Process to release unmanaged resources.</param>
修正しました！
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/a41a670521da13659515ca79ef451a16771024ad

2023-01-26 04:04 UTC, kiyohome commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:b8d918b3ff5e05e4ba23a5c2512f52fe",
FWの1番根っこはCore.Loggingでいいと思います。
CommonはStageNavigationと似たような位置づけです。
AWSにログを出したい場合はIntegration.Logging.AWSなど、Integrationとして作った方がいいと考えてました。

2023-01-26 04:04 UTC, kiyohome commented on Tests/Runtime/Extreal.Core.Common.Test.asmdef
> +    ],
テストコードもするんでしたっけ？入れて見直しときます。

2023-01-26 04:07 UTC, kiyohome commented on Tests/Runtime/System/ClassWithUnmanaged.cs
> +        protected override void ReleaseUnmanagedResources() => ++UnmanagedTimes;
GC.WaitForPendingFinalizersとかアレコレ試していた時の名残で意図ないので後置に戻しときます。

2023-01-26 04:09 UTC, kiyohome commented on Tests/Runtime/Extreal.Core.Common.Test.asmdef
> +    ],
入れました！
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/879cb211137f36575a9bc5b58df63c58f684cc28

2023-01-26 04:12 UTC, kiyohome commented on Tests/Runtime/System/ClassWithUnmanaged.cs
> +        protected override void ReleaseUnmanagedResources() => ++UnmanagedTimes;
戻しました！
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/1dc77bc501bbef8e9b66c91a47602dbf5e798966

2023-01-26 04:15 UTC, kiyohome commented on Tests/Runtime/System/DisposableBaseTest.cs
> +            }
はじめは[Test]でGC.WaitForPendingFinalizers メソッドを使えば大丈夫だろうと思ってやってみましたが、モジュール全体、クラス単位、メソッド単位でテストを複数回実行するとアサート失敗でテストが不定期に落ちて（1回目は通るけど、2回目以降が落ちることが多い）不安定だったので、yield return nullでテストするように統一しました。
GC.WaitForPendingFinalizersを消しましょうか。

2023-01-26 04:21 UTC, kiyohome commented on Tests/Runtime/System/DisposableBaseTest.cs
> +            }
紛らわしいので消しました！
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/46ed660e843307e49eeeeb84cb48d8164c59c790

2023-01-26 04:22 UTC, kiyohome commented on Tests/Runtime/System/DisposableBaseTest.cs
> +        }
GC.WaitForPendingFinalizersを消したのでこのままにしようと思いますが、いかがでしょうか？

2023-01-26 06:25 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:9ea0cf1287a9c944c989c3cff60f15f3"
確認しました！

2023-01-26 06:27 UTC, sus-taguchi-t commented on Runtime/System/DisposableBase.cs
> +        protected DisposableBase()
確認しました！

2023-01-26 06:27 UTC, sus-taguchi-t commented on Runtime/System/SafeDisposer.cs
> +        /// <param name="releaseUnmanagedResources">Process to release unmanaged resources.</param>
確認しました！

2023-01-26 06:29 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Common.asmdef
> +        "GUID:b8d918b3ff5e05e4ba23a5c2512f52fe",
分かりました！
良いと思います。

2023-01-26 06:29 UTC, sus-taguchi-t commented on Tests/Runtime/Extreal.Core.Common.Test.asmdef
> +    ],
確認しました！

2023-01-26 06:31 UTC, sus-taguchi-t commented on Tests/Runtime/System/ClassWithUnmanaged.cs
> +        protected override void ReleaseUnmanagedResources() => ++UnmanagedTimes;
確認しました！

2023-01-26 06:33 UTC, sus-taguchi-t commented on Tests/Runtime/System/DisposableBaseTest.cs
> +            }
確認しました！

2023-01-26 06:39 UTC, sus-taguchi-t commented on Tests/Runtime/System/DisposableBaseTest.cs
> +        }
69 行目で `ClassWithUnmanaged.UnmanagedTimes == 1` が断言されているため while 文の条件文はいつでも失敗します。
`GC.WaitForPendingFinalizers` をなくしたことで却って GC が動くか動かないかすら分からない状態でテストが終了してしまい、テストの意味がなくなってしまっています。

2023-01-26 06:57 UTC, kiyohome commented on Tests/Runtime/System/DisposableBaseTest.cs
> +        }
見直しました、いかがでしょうか？
https://github.com/extreal-dev/Extreal.Core.Common/pull/1/commits/6b3537eb5260d5c023f971c68c0589ee1e3b6f4b

2023-01-26 07:00 UTC, sus-taguchi-t commented on Tests/Runtime/System/DisposableBaseTest.cs
> +        }
確認しました！

2023-01-26 07:41 UTC, kiyohome approved these changes

2023-01-26 08:22 UTC, merged