IObservableのSubscribeをフックできるようにする
extreal-dev/Extreal.Core.Common pull request #6
Opened 2023-05-22 15:15 UTC by kiyohome

# 何の変更を加えましたか？

- ユーザ操作イベントのログ収集をできるように、IObservableのSubscribeをフックできる機能をIObservableに追加しました。
- ReactiveProperyやSubjectのラッパを作ってイベント通知側で実現することを検討しましたが、次の理由によりSubscribe側でログ収集を入れる想定にしました。
  - ログ収集に必要なデータ加工やどのイベントを送るのかはアプリ要件に依存して決まるため。
  - イベント通知側が通知したイベントをどう使うのかを意識するのが役割として不自然
- 今回追加したHookメソッドはUniRxのDoメソッドと似ていますが、フックで例外が発生してもSubscribeの処理に影響を与えない点のみ異なります。

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました
  - サンプルなし

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
  - Holidayに反映するのみのため不要
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

- GuideとHolidayはこのPRで確認が取れてから実施します。

2023-05-23 05:59 UTC, kiyohome commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +            point.Hook(hook).Subscribe(onNext).AddTo(disposables);
UniRxのDoで実現するとSubscribeされないと呼ばれない。
そのため、複数Subscribeしている場合にどこに入れるのか管理しないといけなくなる。
Subscribeでやる方がいいのではないか？

2023-05-23 05:59 UTC, kiyohome commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +            point.Hook(hook).Subscribe(onNext).AddTo(disposables);
フックで入れる想定の処理はユーザー利用状況可視化のためのデータ送信など。
本当に必要な処理ではないので、フックでエラーが発生してもSubscribeには影響を与えたくない。
Subscribeで例外が発生しないかたちで対応してみる。

2023-05-23 13:27 UTC, kiyohome commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +            point.Hook(hook).Subscribe(onNext).AddTo(disposables);
対応しました。
https://github.com/extreal-dev/Extreal.Core.Common/pull/6/commits/bbf12f918d8bafa7fd139cad9afa21cdc7b7f4a2

2023-05-31 00:17 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +                    Logger.LogDebug("Error occurred on hook", e);
実際にやってみて、Unity Editorで実行中にDebugだとエラーに気付きにくいので、出力はErrorで出した方がいいと感じました。
対応する場合は、IsDebugとLogErrorでレベルを変えているのでミスでないことが分かるようにコメントを入れましょう。

2023-05-31 06:16 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +                    Logger.LogDebug("Error occurred on hook", e);
Fixed!
https://github.com/extreal-dev/Extreal.Core.Common/pull/6/commits/4d7116a553551e828167f196da8e81c980598e83

2023-06-12 06:13 UTC, sus-taguchi-t requested changes

2023-06-12 06:13 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +    public static class ObservableExtensions
`Observable` クラスでなく `IObservable` インターフェースの拡張メソッドのため、`IObservableExtensions` の方が良いと思います。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                hook.Invoke(value);
`hook(value)` で良いと思いました。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                    // Output the log at the Error level so that the developer is aware of the error during development.
Output the log at the Error level
-> Outputs the log with Error level

2023-06-12 06:13 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                    Logger.LogError("Error occurred on hook", e);
Error occurred -> Error has occurred

エラー文ではこちらの言い回しの方がよく見かける気がします。

2023-06-12 06:13 UTC, sus-taguchi-t commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +using Extreal.Core.Common.Hook;
`Extreal.Core.Common.Hook` の using ディレクティブは不要です。
`namespace Extreal.Core.Common.Hook.Test` という名前空間に含まれているためです。

2023-06-12 06:47 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +    public static class ObservableExtensions
UniRxに合わせたのと、インタフェースの実態（インスタンス）に対して拡張メソッドを適用するのでこの名前でいいと思いますが、いかがですか？
https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/Observer.cs#L405

2023-06-12 06:49 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +                hook.Invoke(value);
このあたりの静的チェックでできない部分は、統一するならルール化が必要になるので、リスクが無ければどちらでもいいことにしたいのですが、いかがでしょうか？

2023-06-12 12:57 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +                    // Output the log at the Error level so that the developer is aware of the error during development.
Fixed!
https://github.com/extreal-dev/Extreal.Core.Common/pull/6/commits/7cb31dcdf999c9094ac174b92e764aaa1a1f364e#diff-f6972e5660854e985e9f9891bd04aa115013eb8ae0a198b0fb06c01cbe986166R46

2023-06-12 12:57 UTC, kiyohome commented on Runtime/Hook/ObservableExtensions.cs
> +                    Logger.LogError("Error occurred on hook", e);
Fixed!
https://github.com/extreal-dev/Extreal.Core.Common/pull/6/commits/7cb31dcdf999c9094ac174b92e764aaa1a1f364e#diff-f6972e5660854e985e9f9891bd04aa115013eb8ae0a198b0fb06c01cbe986166R47

2023-06-12 12:58 UTC, kiyohome commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +using Extreal.Core.Common.Hook;
Fixed!
https://github.com/extreal-dev/Extreal.Core.Common/pull/6/commits/7cb31dcdf999c9094ac174b92e764aaa1a1f364e#diff-968763ba43b295672eb337ee6e0738ef6e8e7cac4556b14199f9d5d553f5a13fL3

2023-06-13 00:39 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +    public static class ObservableExtensions
そのままで良いと思います。

2023-06-13 00:40 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                hook.Invoke(value);
ルール化した方がリスクが高いと思うのでこのままで良いと思います。

2023-06-13 00:40 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                    // Output the log at the Error level so that the developer is aware of the error during development.
確認しました。

2023-06-13 00:41 UTC, sus-taguchi-t commented on Runtime/Hook/ObservableExtensions.cs
> +                    Logger.LogError("Error occurred on hook", e);
確認しました。

2023-06-13 00:41 UTC, sus-taguchi-t commented on Tests/Runtime/Hook/ObservableExtensionsTest.cs
> +using Extreal.Core.Common.Hook;
確認しました。

2023-06-13 00:45 UTC, sus-taguchi-t approved these changes

2023-06-13 00:45 UTC, merged